# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import sync_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='app_notification_specifics.proto',
  package='sync_pb',
  serialized_pb='\n app_notification_specifics.proto\x12\x07sync_pb\x1a\nsync.proto\"\x95\x01\n\x0f\x41ppNotification\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x02 \x01(\t\x12\x1d\n\x15\x63reation_timestamp_ms\x18\x03 \x01(\x03\x12\r\n\x05title\x18\x04 \x01(\t\x12\x11\n\tbody_text\x18\x05 \x01(\t\x12\x10\n\x08link_url\x18\x06 \x01(\t\x12\x11\n\tlink_text\x18\x07 \x01(\t:N\n\x10\x61pp_notification\x12\x18.sync_pb.EntitySpecifics\x18\x80\xe1\x02 \x01(\x0b\x32\x18.sync_pb.AppNotificationB\x04H\x03X\x01')


APP_NOTIFICATION_FIELD_NUMBER = 45184
app_notification = descriptor.FieldDescriptor(
  name='app_notification', full_name='sync_pb.app_notification', index=0,
  number=45184, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_APPNOTIFICATION = descriptor.Descriptor(
  name='AppNotification',
  full_name='sync_pb.AppNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='guid', full_name='sync_pb.AppNotification.guid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='app_id', full_name='sync_pb.AppNotification.app_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='creation_timestamp_ms', full_name='sync_pb.AppNotification.creation_timestamp_ms', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='title', full_name='sync_pb.AppNotification.title', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='body_text', full_name='sync_pb.AppNotification.body_text', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='link_url', full_name='sync_pb.AppNotification.link_url', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='link_text', full_name='sync_pb.AppNotification.link_text', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=58,
  serialized_end=207,
)

DESCRIPTOR.message_types_by_name['AppNotification'] = _APPNOTIFICATION

class AppNotification(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _APPNOTIFICATION
  
  # @@protoc_insertion_point(class_scope:sync_pb.AppNotification)

app_notification.message_type = _APPNOTIFICATION
sync_pb2.EntitySpecifics.RegisterExtension(app_notification)
# @@protoc_insertion_point(module_scope)
