# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import sync_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='autofill_specifics.proto',
  package='sync_pb',
  serialized_pb='\n\x18\x61utofill_specifics.proto\x12\x07sync_pb\x1a\nsync.proto\"\x8c\x03\n\x18\x41utofillProfileSpecifics\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0c\n\x04guid\x18\x0f \x01(\t\x12\x12\n\nname_first\x18\x02 \x03(\t\x12\x13\n\x0bname_middle\x18\x03 \x03(\t\x12\x11\n\tname_last\x18\x04 \x03(\t\x12\x15\n\remail_address\x18\x05 \x03(\t\x12\x14\n\x0c\x63ompany_name\x18\x06 \x01(\t\x12\x1a\n\x12\x61\x64\x64ress_home_line1\x18\x07 \x01(\t\x12\x1a\n\x12\x61\x64\x64ress_home_line2\x18\x08 \x01(\t\x12\x19\n\x11\x61\x64\x64ress_home_city\x18\t \x01(\t\x12\x1a\n\x12\x61\x64\x64ress_home_state\x18\n \x01(\t\x12\x18\n\x10\x61\x64\x64ress_home_zip\x18\x0b \x01(\t\x12\x1c\n\x14\x61\x64\x64ress_home_country\x18\x0c \x01(\t\x12\x1f\n\x17phone_home_whole_number\x18\r \x03(\t\x12\"\n\x16phone_fax_whole_number\x18\x0e \x01(\tB\x02\x18\x01\"}\n\x11\x41utofillSpecifics\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x17\n\x0fusage_timestamp\x18\x03 \x03(\x03\x12\x32\n\x07profile\x18\x04 \x01(\x0b\x32!.sync_pb.AutofillProfileSpecifics:H\n\x08\x61utofill\x12\x18.sync_pb.EntitySpecifics\x18\xf1\xf7\x01 \x01(\x0b\x32\x1a.sync_pb.AutofillSpecifics:W\n\x10\x61utofill_profile\x12\x18.sync_pb.EntitySpecifics\x18\xcf\xf3\x03 \x01(\x0b\x32!.sync_pb.AutofillProfileSpecificsB\x04H\x03X\x01')


AUTOFILL_FIELD_NUMBER = 31729
autofill = descriptor.FieldDescriptor(
  name='autofill', full_name='sync_pb.autofill', index=0,
  number=31729, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
AUTOFILL_PROFILE_FIELD_NUMBER = 63951
autofill_profile = descriptor.FieldDescriptor(
  name='autofill_profile', full_name='sync_pb.autofill_profile', index=1,
  number=63951, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_AUTOFILLPROFILESPECIFICS = descriptor.Descriptor(
  name='AutofillProfileSpecifics',
  full_name='sync_pb.AutofillProfileSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='label', full_name='sync_pb.AutofillProfileSpecifics.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='guid', full_name='sync_pb.AutofillProfileSpecifics.guid', index=1,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name_first', full_name='sync_pb.AutofillProfileSpecifics.name_first', index=2,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name_middle', full_name='sync_pb.AutofillProfileSpecifics.name_middle', index=3,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name_last', full_name='sync_pb.AutofillProfileSpecifics.name_last', index=4,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='email_address', full_name='sync_pb.AutofillProfileSpecifics.email_address', index=5,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='company_name', full_name='sync_pb.AutofillProfileSpecifics.company_name', index=6,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address_home_line1', full_name='sync_pb.AutofillProfileSpecifics.address_home_line1', index=7,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address_home_line2', full_name='sync_pb.AutofillProfileSpecifics.address_home_line2', index=8,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address_home_city', full_name='sync_pb.AutofillProfileSpecifics.address_home_city', index=9,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address_home_state', full_name='sync_pb.AutofillProfileSpecifics.address_home_state', index=10,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address_home_zip', full_name='sync_pb.AutofillProfileSpecifics.address_home_zip', index=11,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address_home_country', full_name='sync_pb.AutofillProfileSpecifics.address_home_country', index=12,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='phone_home_whole_number', full_name='sync_pb.AutofillProfileSpecifics.phone_home_whole_number', index=13,
      number=13, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='phone_fax_whole_number', full_name='sync_pb.AutofillProfileSpecifics.phone_fax_whole_number', index=14,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\030\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=50,
  serialized_end=446,
)


_AUTOFILLSPECIFICS = descriptor.Descriptor(
  name='AutofillSpecifics',
  full_name='sync_pb.AutofillSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='sync_pb.AutofillSpecifics.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='sync_pb.AutofillSpecifics.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='usage_timestamp', full_name='sync_pb.AutofillSpecifics.usage_timestamp', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='profile', full_name='sync_pb.AutofillSpecifics.profile', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=448,
  serialized_end=573,
)

_AUTOFILLSPECIFICS.fields_by_name['profile'].message_type = _AUTOFILLPROFILESPECIFICS
DESCRIPTOR.message_types_by_name['AutofillProfileSpecifics'] = _AUTOFILLPROFILESPECIFICS
DESCRIPTOR.message_types_by_name['AutofillSpecifics'] = _AUTOFILLSPECIFICS

class AutofillProfileSpecifics(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTOFILLPROFILESPECIFICS
  
  # @@protoc_insertion_point(class_scope:sync_pb.AutofillProfileSpecifics)

class AutofillSpecifics(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTOFILLSPECIFICS
  
  # @@protoc_insertion_point(class_scope:sync_pb.AutofillSpecifics)

autofill.message_type = _AUTOFILLSPECIFICS
sync_pb2.EntitySpecifics.RegisterExtension(autofill)
autofill_profile.message_type = _AUTOFILLPROFILESPECIFICS
sync_pb2.EntitySpecifics.RegisterExtension(autofill_profile)
# @@protoc_insertion_point(module_scope)
