# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import sync_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='bookmark_specifics.proto',
  package='sync_pb',
  serialized_pb='\n\x18\x62ookmark_specifics.proto\x12\x07sync_pb\x1a\nsync.proto\"@\n\x11\x42ookmarkSpecifics\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0f\n\x07\x66\x61vicon\x18\x02 \x01(\x0c\x12\r\n\x05title\x18\x03 \x01(\t:H\n\x08\x62ookmark\x12\x18.sync_pb.EntitySpecifics\x18\x88\x81\x02 \x01(\x0b\x32\x1a.sync_pb.BookmarkSpecificsB\x04H\x03X\x01')


BOOKMARK_FIELD_NUMBER = 32904
bookmark = descriptor.FieldDescriptor(
  name='bookmark', full_name='sync_pb.bookmark', index=0,
  number=32904, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_BOOKMARKSPECIFICS = descriptor.Descriptor(
  name='BookmarkSpecifics',
  full_name='sync_pb.BookmarkSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='url', full_name='sync_pb.BookmarkSpecifics.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='favicon', full_name='sync_pb.BookmarkSpecifics.favicon', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='title', full_name='sync_pb.BookmarkSpecifics.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=49,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['BookmarkSpecifics'] = _BOOKMARKSPECIFICS

class BookmarkSpecifics(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BOOKMARKSPECIFICS
  
  # @@protoc_insertion_point(class_scope:sync_pb.BookmarkSpecifics)

bookmark.message_type = _BOOKMARKSPECIFICS
sync_pb2.EntitySpecifics.RegisterExtension(bookmark)
# @@protoc_insertion_point(module_scope)
