# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='client_debug_info.proto',
  package='sync_pb',
  serialized_pb='\n\x17\x63lient_debug_info.proto\x12\x07sync_pb\"a\n\x1bSyncCycleCompletedEventInfo\x12\x1e\n\x16num_blocking_conflicts\x18\x02 \x01(\x05\x12\"\n\x1anum_non_blocking_conflicts\x18\x03 \x01(\x05\"\xfa\x02\n\x0e\x44\x65\x62ugEventInfo\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.sync_pb.DebugEventInfo.EventType\x12M\n\x1fsync_cycle_completed_event_info\x18\x02 \x01(\x0b\x32$.sync_pb.SyncCycleCompletedEventInfo\"\xe7\x01\n\tEventType\x12\x0e\n\nAUTH_ERROR\x10\x01\x12\x11\n\rUPDATED_TOKEN\x10\x02\x12\x17\n\x13PASSPHRASE_REQUIRED\x10\x03\x12\x17\n\x13PASSPHRASE_ACCEPTED\x10\x04\x12\x1b\n\x17INITIALIZATION_COMPLETE\x10\x05\x12\x1c\n\x18STOP_SYNCING_PERMANENTLY\x10\x06\x12\x1b\n\x17\x45NCRYPTED_TYPES_CHANGED\x10\t\x12\x17\n\x13\x45NCRYPTION_COMPLETE\x10\x07\x12\x14\n\x10\x41\x43TIONABLE_ERROR\x10\x08\"\x91\x01\n\tDebugInfo\x12\'\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x17.sync_pb.DebugEventInfo\x12\x1b\n\x13\x63ryptographer_ready\x18\x02 \x01(\x08\x12&\n\x1e\x63ryptographer_has_pending_keys\x18\x03 \x01(\x08\x12\x16\n\x0e\x65vents_dropped\x18\x04 \x01(\x08\x42\x04H\x03X\x01')



_DEBUGEVENTINFO_EVENTTYPE = descriptor.EnumDescriptor(
  name='EventType',
  full_name='sync_pb.DebugEventInfo.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='AUTH_ERROR', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UPDATED_TOKEN', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PASSPHRASE_REQUIRED', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PASSPHRASE_ACCEPTED', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INITIALIZATION_COMPLETE', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STOP_SYNCING_PERMANENTLY', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ENCRYPTED_TYPES_CHANGED', index=6, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ENCRYPTION_COMPLETE', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIONABLE_ERROR', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=283,
  serialized_end=514,
)


_SYNCCYCLECOMPLETEDEVENTINFO = descriptor.Descriptor(
  name='SyncCycleCompletedEventInfo',
  full_name='sync_pb.SyncCycleCompletedEventInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='num_blocking_conflicts', full_name='sync_pb.SyncCycleCompletedEventInfo.num_blocking_conflicts', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='num_non_blocking_conflicts', full_name='sync_pb.SyncCycleCompletedEventInfo.num_non_blocking_conflicts', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=133,
)


_DEBUGEVENTINFO = descriptor.Descriptor(
  name='DebugEventInfo',
  full_name='sync_pb.DebugEventInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='sync_pb.DebugEventInfo.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sync_cycle_completed_event_info', full_name='sync_pb.DebugEventInfo.sync_cycle_completed_event_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DEBUGEVENTINFO_EVENTTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=136,
  serialized_end=514,
)


_DEBUGINFO = descriptor.Descriptor(
  name='DebugInfo',
  full_name='sync_pb.DebugInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='events', full_name='sync_pb.DebugInfo.events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cryptographer_ready', full_name='sync_pb.DebugInfo.cryptographer_ready', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cryptographer_has_pending_keys', full_name='sync_pb.DebugInfo.cryptographer_has_pending_keys', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='events_dropped', full_name='sync_pb.DebugInfo.events_dropped', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=517,
  serialized_end=662,
)

_DEBUGEVENTINFO.fields_by_name['type'].enum_type = _DEBUGEVENTINFO_EVENTTYPE
_DEBUGEVENTINFO.fields_by_name['sync_cycle_completed_event_info'].message_type = _SYNCCYCLECOMPLETEDEVENTINFO
_DEBUGEVENTINFO_EVENTTYPE.containing_type = _DEBUGEVENTINFO;
_DEBUGINFO.fields_by_name['events'].message_type = _DEBUGEVENTINFO
DESCRIPTOR.message_types_by_name['SyncCycleCompletedEventInfo'] = _SYNCCYCLECOMPLETEDEVENTINFO
DESCRIPTOR.message_types_by_name['DebugEventInfo'] = _DEBUGEVENTINFO
DESCRIPTOR.message_types_by_name['DebugInfo'] = _DEBUGINFO

class SyncCycleCompletedEventInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SYNCCYCLECOMPLETEDEVENTINFO
  
  # @@protoc_insertion_point(class_scope:sync_pb.SyncCycleCompletedEventInfo)

class DebugEventInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEBUGEVENTINFO
  
  # @@protoc_insertion_point(class_scope:sync_pb.DebugEventInfo)

class DebugInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEBUGINFO
  
  # @@protoc_insertion_point(class_scope:sync_pb.DebugInfo)

# @@protoc_insertion_point(module_scope)
