# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='client_commands.proto',
  package='sync_pb',
  serialized_pb='\n\x15\x63lient_commands.proto\x12\x07sync_pb\"\xba\x01\n\rClientCommand\x12\x1e\n\x16set_sync_poll_interval\x18\x01 \x01(\x05\x12#\n\x1bset_sync_long_poll_interval\x18\x02 \x01(\x05\x12\x1d\n\x15max_commit_batch_size\x18\x03 \x01(\x05\x12%\n\x1dsessions_commit_delay_seconds\x18\x04 \x01(\x05\x12\x1e\n\x16throttle_delay_seconds\x18\x05 \x01(\x05\x42\x04H\x03X\x01')




_CLIENTCOMMAND = descriptor.Descriptor(
  name='ClientCommand',
  full_name='sync_pb.ClientCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='set_sync_poll_interval', full_name='sync_pb.ClientCommand.set_sync_poll_interval', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='set_sync_long_poll_interval', full_name='sync_pb.ClientCommand.set_sync_long_poll_interval', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_commit_batch_size', full_name='sync_pb.ClientCommand.max_commit_batch_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sessions_commit_delay_seconds', full_name='sync_pb.ClientCommand.sessions_commit_delay_seconds', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='throttle_delay_seconds', full_name='sync_pb.ClientCommand.throttle_delay_seconds', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=221,
)

DESCRIPTOR.message_types_by_name['ClientCommand'] = _CLIENTCOMMAND

class ClientCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLIENTCOMMAND
  
  # @@protoc_insertion_point(class_scope:sync_pb.ClientCommand)

# @@protoc_insertion_point(module_scope)
