# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import sync_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='extension_specifics.proto',
  package='sync_pb',
  serialized_pb='\n\x19\x65xtension_specifics.proto\x12\x07sync_pb\x1a\nsync.proto\"\x7f\n\x12\x45xtensionSpecifics\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x12\n\nupdate_url\x18\x03 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x04 \x01(\x08\x12\x19\n\x11incognito_enabled\x18\x05 \x01(\x08\x12\x0c\n\x04name\x18\x06 \x01(\t:J\n\textension\x12\x18.sync_pb.EntitySpecifics\x18\xf7\xf7\x02 \x01(\x0b\x32\x1b.sync_pb.ExtensionSpecificsB\x04H\x03X\x01')


EXTENSION_FIELD_NUMBER = 48119
extension = descriptor.FieldDescriptor(
  name='extension', full_name='sync_pb.extension', index=0,
  number=48119, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_EXTENSIONSPECIFICS = descriptor.Descriptor(
  name='ExtensionSpecifics',
  full_name='sync_pb.ExtensionSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='sync_pb.ExtensionSpecifics.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='version', full_name='sync_pb.ExtensionSpecifics.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='update_url', full_name='sync_pb.ExtensionSpecifics.update_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='enabled', full_name='sync_pb.ExtensionSpecifics.enabled', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='incognito_enabled', full_name='sync_pb.ExtensionSpecifics.incognito_enabled', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='sync_pb.ExtensionSpecifics.name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=50,
  serialized_end=177,
)

DESCRIPTOR.message_types_by_name['ExtensionSpecifics'] = _EXTENSIONSPECIFICS

class ExtensionSpecifics(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXTENSIONSPECIFICS
  
  # @@protoc_insertion_point(class_scope:sync_pb.ExtensionSpecifics)

extension.message_type = _EXTENSIONSPECIFICS
sync_pb2.EntitySpecifics.RegisterExtension(extension)
# @@protoc_insertion_point(module_scope)
