# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import encryption_pb2
import sync_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='nigori_specifics.proto',
  package='sync_pb',
  serialized_pb='\n\x16nigori_specifics.proto\x12\x07sync_pb\x1a\x10\x65ncryption.proto\x1a\nsync.proto\"T\n\tNigoriKey\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08user_key\x18\x02 \x01(\x0c\x12\x16\n\x0e\x65ncryption_key\x18\x03 \x01(\x0c\x12\x0f\n\x07mac_key\x18\x04 \x01(\x0c\"/\n\x0cNigoriKeyBag\x12\x1f\n\x03key\x18\x02 \x03(\x0b\x32\x12.sync_pb.NigoriKey\"_\n\x11\x44\x65viceInformation\x12\x12\n\ncache_guid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08platform\x18\x03 \x01(\t\x12\x16\n\x0e\x63hrome_version\x18\x04 \x01(\t\"\xbf\x04\n\x0fNigoriSpecifics\x12)\n\tencrypted\x18\x01 \x01(\x0b\x32\x16.sync_pb.EncryptedData\x12!\n\x19using_explicit_passphrase\x18\x02 \x01(\x08\x12\x19\n\x11\x65ncrypt_bookmarks\x18\r \x01(\x08\x12\x1b\n\x13\x65ncrypt_preferences\x18\x0e \x01(\x08\x12 \n\x18\x65ncrypt_autofill_profile\x18\x0f \x01(\x08\x12\x18\n\x10\x65ncrypt_autofill\x18\x10 \x01(\x08\x12\x16\n\x0e\x65ncrypt_themes\x18\x11 \x01(\x08\x12\x1a\n\x12\x65ncrypt_typed_urls\x18\x12 \x01(\x08\x12\x1a\n\x12\x65ncrypt_extensions\x18\x13 \x01(\x08\x12\x18\n\x10\x65ncrypt_sessions\x18\x14 \x01(\x08\x12\x14\n\x0c\x65ncrypt_apps\x18\x15 \x01(\x08\x12\x1e\n\x16\x65ncrypt_search_engines\x18\x16 \x01(\x08\x12\x11\n\tsync_tabs\x18\x17 \x01(\x08\x12\x1a\n\x12\x65ncrypt_everything\x18\x18 \x01(\x08\x12\"\n\x1a\x65ncrypt_extension_settings\x18\x19 \x01(\x08\x12!\n\x19\x65ncrypt_app_notifications\x18\x1a \x01(\x08\x12\x1c\n\x14\x65ncrypt_app_settings\x18\x1b \x01(\x08\x12\x36\n\x12\x64\x65vice_information\x18\x1c \x03(\x0b\x32\x1a.sync_pb.DeviceInformation:D\n\x06nigori\x12\x18.sync_pb.EntitySpecifics\x18\x81\xf5\x02 \x01(\x0b\x32\x18.sync_pb.NigoriSpecificsB\x04H\x03X\x01')


NIGORI_FIELD_NUMBER = 47745
nigori = descriptor.FieldDescriptor(
  name='nigori', full_name='sync_pb.nigori', index=0,
  number=47745, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_NIGORIKEY = descriptor.Descriptor(
  name='NigoriKey',
  full_name='sync_pb.NigoriKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='sync_pb.NigoriKey.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_key', full_name='sync_pb.NigoriKey.user_key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='encryption_key', full_name='sync_pb.NigoriKey.encryption_key', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mac_key', full_name='sync_pb.NigoriKey.mac_key', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=65,
  serialized_end=149,
)


_NIGORIKEYBAG = descriptor.Descriptor(
  name='NigoriKeyBag',
  full_name='sync_pb.NigoriKeyBag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='sync_pb.NigoriKeyBag.key', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=151,
  serialized_end=198,
)


_DEVICEINFORMATION = descriptor.Descriptor(
  name='DeviceInformation',
  full_name='sync_pb.DeviceInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='cache_guid', full_name='sync_pb.DeviceInformation.cache_guid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='sync_pb.DeviceInformation.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='platform', full_name='sync_pb.DeviceInformation.platform', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='chrome_version', full_name='sync_pb.DeviceInformation.chrome_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=200,
  serialized_end=295,
)


_NIGORISPECIFICS = descriptor.Descriptor(
  name='NigoriSpecifics',
  full_name='sync_pb.NigoriSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='encrypted', full_name='sync_pb.NigoriSpecifics.encrypted', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='using_explicit_passphrase', full_name='sync_pb.NigoriSpecifics.using_explicit_passphrase', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='encrypt_bookmarks', full_name='sync_pb.NigoriSpecifics.encrypt_bookmarks', index=2,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='encrypt_preferences', full_name='sync_pb.NigoriSpecifics.encrypt_preferences', index=3,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='encrypt_autofill_profile', full_name='sync_pb.NigoriSpecifics.encrypt_autofill_profile', index=4,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='encrypt_autofill', full_name='sync_pb.NigoriSpecifics.encrypt_autofill', index=5,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='encrypt_themes', full_name='sync_pb.NigoriSpecifics.encrypt_themes', index=6,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='encrypt_typed_urls', full_name='sync_pb.NigoriSpecifics.encrypt_typed_urls', index=7,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='encrypt_extensions', full_name='sync_pb.NigoriSpecifics.encrypt_extensions', index=8,
      number=19, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='encrypt_sessions', full_name='sync_pb.NigoriSpecifics.encrypt_sessions', index=9,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='encrypt_apps', full_name='sync_pb.NigoriSpecifics.encrypt_apps', index=10,
      number=21, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='encrypt_search_engines', full_name='sync_pb.NigoriSpecifics.encrypt_search_engines', index=11,
      number=22, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sync_tabs', full_name='sync_pb.NigoriSpecifics.sync_tabs', index=12,
      number=23, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='encrypt_everything', full_name='sync_pb.NigoriSpecifics.encrypt_everything', index=13,
      number=24, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='encrypt_extension_settings', full_name='sync_pb.NigoriSpecifics.encrypt_extension_settings', index=14,
      number=25, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='encrypt_app_notifications', full_name='sync_pb.NigoriSpecifics.encrypt_app_notifications', index=15,
      number=26, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='encrypt_app_settings', full_name='sync_pb.NigoriSpecifics.encrypt_app_settings', index=16,
      number=27, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='device_information', full_name='sync_pb.NigoriSpecifics.device_information', index=17,
      number=28, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=298,
  serialized_end=873,
)

_NIGORIKEYBAG.fields_by_name['key'].message_type = _NIGORIKEY
_NIGORISPECIFICS.fields_by_name['encrypted'].message_type = encryption_pb2._ENCRYPTEDDATA
_NIGORISPECIFICS.fields_by_name['device_information'].message_type = _DEVICEINFORMATION
DESCRIPTOR.message_types_by_name['NigoriKey'] = _NIGORIKEY
DESCRIPTOR.message_types_by_name['NigoriKeyBag'] = _NIGORIKEYBAG
DESCRIPTOR.message_types_by_name['DeviceInformation'] = _DEVICEINFORMATION
DESCRIPTOR.message_types_by_name['NigoriSpecifics'] = _NIGORISPECIFICS

class NigoriKey(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NIGORIKEY
  
  # @@protoc_insertion_point(class_scope:sync_pb.NigoriKey)

class NigoriKeyBag(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NIGORIKEYBAG
  
  # @@protoc_insertion_point(class_scope:sync_pb.NigoriKeyBag)

class DeviceInformation(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEVICEINFORMATION
  
  # @@protoc_insertion_point(class_scope:sync_pb.DeviceInformation)

class NigoriSpecifics(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NIGORISPECIFICS
  
  # @@protoc_insertion_point(class_scope:sync_pb.NigoriSpecifics)

nigori.message_type = _NIGORISPECIFICS
sync_pb2.EntitySpecifics.RegisterExtension(nigori)
# @@protoc_insertion_point(module_scope)
