# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import encryption_pb2
import sync_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='password_specifics.proto',
  package='sync_pb',
  serialized_pb='\n\x18password_specifics.proto\x12\x07sync_pb\x1a\x10\x65ncryption.proto\x1a\nsync.proto\"\x92\x02\n\x15PasswordSpecificsData\x12\x0e\n\x06scheme\x18\x01 \x01(\x05\x12\x14\n\x0csignon_realm\x18\x02 \x01(\t\x12\x0e\n\x06origin\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x04 \x01(\t\x12\x18\n\x10username_element\x18\x05 \x01(\t\x12\x16\n\x0eusername_value\x18\x06 \x01(\t\x12\x18\n\x10password_element\x18\x07 \x01(\t\x12\x16\n\x0epassword_value\x18\x08 \x01(\t\x12\x11\n\tssl_valid\x18\t \x01(\x08\x12\x11\n\tpreferred\x18\n \x01(\x08\x12\x14\n\x0c\x64\x61te_created\x18\x0b \x01(\x03\x12\x13\n\x0b\x62lacklisted\x18\x0c \x01(\x08\">\n\x11PasswordSpecifics\x12)\n\tencrypted\x18\x01 \x01(\x0b\x32\x16.sync_pb.EncryptedData:H\n\x08password\x12\x18.sync_pb.EntitySpecifics\x18\xb1\xe6\x02 \x01(\x0b\x32\x1a.sync_pb.PasswordSpecificsB\x04H\x03X\x01')


PASSWORD_FIELD_NUMBER = 45873
password = descriptor.FieldDescriptor(
  name='password', full_name='sync_pb.password', index=0,
  number=45873, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_PASSWORDSPECIFICSDATA = descriptor.Descriptor(
  name='PasswordSpecificsData',
  full_name='sync_pb.PasswordSpecificsData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='scheme', full_name='sync_pb.PasswordSpecificsData.scheme', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='signon_realm', full_name='sync_pb.PasswordSpecificsData.signon_realm', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='origin', full_name='sync_pb.PasswordSpecificsData.origin', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='action', full_name='sync_pb.PasswordSpecificsData.action', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='username_element', full_name='sync_pb.PasswordSpecificsData.username_element', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='username_value', full_name='sync_pb.PasswordSpecificsData.username_value', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='password_element', full_name='sync_pb.PasswordSpecificsData.password_element', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='password_value', full_name='sync_pb.PasswordSpecificsData.password_value', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ssl_valid', full_name='sync_pb.PasswordSpecificsData.ssl_valid', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='preferred', full_name='sync_pb.PasswordSpecificsData.preferred', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='date_created', full_name='sync_pb.PasswordSpecificsData.date_created', index=10,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='blacklisted', full_name='sync_pb.PasswordSpecificsData.blacklisted', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=68,
  serialized_end=342,
)


_PASSWORDSPECIFICS = descriptor.Descriptor(
  name='PasswordSpecifics',
  full_name='sync_pb.PasswordSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='encrypted', full_name='sync_pb.PasswordSpecifics.encrypted', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=344,
  serialized_end=406,
)

_PASSWORDSPECIFICS.fields_by_name['encrypted'].message_type = encryption_pb2._ENCRYPTEDDATA
DESCRIPTOR.message_types_by_name['PasswordSpecificsData'] = _PASSWORDSPECIFICSDATA
DESCRIPTOR.message_types_by_name['PasswordSpecifics'] = _PASSWORDSPECIFICS

class PasswordSpecificsData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PASSWORDSPECIFICSDATA
  
  # @@protoc_insertion_point(class_scope:sync_pb.PasswordSpecificsData)

class PasswordSpecifics(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PASSWORDSPECIFICS
  
  # @@protoc_insertion_point(class_scope:sync_pb.PasswordSpecifics)

password.message_type = _PASSWORDSPECIFICS
sync_pb2.EntitySpecifics.RegisterExtension(password)
# @@protoc_insertion_point(module_scope)
