# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import sync_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='preference_specifics.proto',
  package='sync_pb',
  serialized_pb='\n\x1apreference_specifics.proto\x12\x07sync_pb\x1a\nsync.proto\"2\n\x13PreferenceSpecifics\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:L\n\npreference\x12\x18.sync_pb.EntitySpecifics\x18\xc6\xa6\x02 \x01(\x0b\x32\x1c.sync_pb.PreferenceSpecificsB\x04H\x03X\x01')


PREFERENCE_FIELD_NUMBER = 37702
preference = descriptor.FieldDescriptor(
  name='preference', full_name='sync_pb.preference', index=0,
  number=37702, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_PREFERENCESPECIFICS = descriptor.Descriptor(
  name='PreferenceSpecifics',
  full_name='sync_pb.PreferenceSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='sync_pb.PreferenceSpecifics.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='sync_pb.PreferenceSpecifics.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=51,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['PreferenceSpecifics'] = _PREFERENCESPECIFICS

class PreferenceSpecifics(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PREFERENCESPECIFICS
  
  # @@protoc_insertion_point(class_scope:sync_pb.PreferenceSpecifics)

preference.message_type = _PREFERENCESPECIFICS
sync_pb2.EntitySpecifics.RegisterExtension(preference)
# @@protoc_insertion_point(module_scope)
