# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import sync_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='search_engine_specifics.proto',
  package='sync_pb',
  serialized_pb='\n\x1dsearch_engine_specifics.proto\x12\x07sync_pb\x1a\nsync.proto\"\xf0\x02\n\x15SearchEngineSpecifics\x12\x12\n\nshort_name\x18\x01 \x01(\t\x12\x0f\n\x07keyword\x18\x02 \x01(\t\x12\x13\n\x0b\x66\x61vicon_url\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x1c\n\x14safe_for_autoreplace\x18\x05 \x01(\x08\x12\x17\n\x0foriginating_url\x18\x06 \x01(\t\x12\x14\n\x0c\x64\x61te_created\x18\x07 \x01(\x03\x12\x17\n\x0finput_encodings\x18\x08 \x01(\t\x12\x1c\n\x14show_in_default_list\x18\t \x01(\x08\x12\x17\n\x0fsuggestions_url\x18\n \x01(\t\x12\x16\n\x0eprepopulate_id\x18\x0b \x01(\x05\x12\x1c\n\x14\x61utogenerate_keyword\x18\x0c \x01(\x08\x12\x13\n\x0binstant_url\x18\x0f \x01(\t\x12\x15\n\rlast_modified\x18\x11 \x01(\x03\x12\x11\n\tsync_guid\x18\x12 \x01(\t:Q\n\rsearch_engine\x12\x18.sync_pb.EntitySpecifics\x18\xa2\xb4\x05 \x01(\x0b\x32\x1e.sync_pb.SearchEngineSpecificsB\x04H\x03X\x01')


SEARCH_ENGINE_FIELD_NUMBER = 88610
search_engine = descriptor.FieldDescriptor(
  name='search_engine', full_name='sync_pb.search_engine', index=0,
  number=88610, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_SEARCHENGINESPECIFICS = descriptor.Descriptor(
  name='SearchEngineSpecifics',
  full_name='sync_pb.SearchEngineSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='short_name', full_name='sync_pb.SearchEngineSpecifics.short_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='keyword', full_name='sync_pb.SearchEngineSpecifics.keyword', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='favicon_url', full_name='sync_pb.SearchEngineSpecifics.favicon_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='url', full_name='sync_pb.SearchEngineSpecifics.url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='safe_for_autoreplace', full_name='sync_pb.SearchEngineSpecifics.safe_for_autoreplace', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='originating_url', full_name='sync_pb.SearchEngineSpecifics.originating_url', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='date_created', full_name='sync_pb.SearchEngineSpecifics.date_created', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='input_encodings', full_name='sync_pb.SearchEngineSpecifics.input_encodings', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='show_in_default_list', full_name='sync_pb.SearchEngineSpecifics.show_in_default_list', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='suggestions_url', full_name='sync_pb.SearchEngineSpecifics.suggestions_url', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='prepopulate_id', full_name='sync_pb.SearchEngineSpecifics.prepopulate_id', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='autogenerate_keyword', full_name='sync_pb.SearchEngineSpecifics.autogenerate_keyword', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='instant_url', full_name='sync_pb.SearchEngineSpecifics.instant_url', index=12,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='last_modified', full_name='sync_pb.SearchEngineSpecifics.last_modified', index=13,
      number=17, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sync_guid', full_name='sync_pb.SearchEngineSpecifics.sync_guid', index=14,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=55,
  serialized_end=423,
)

DESCRIPTOR.message_types_by_name['SearchEngineSpecifics'] = _SEARCHENGINESPECIFICS

class SearchEngineSpecifics(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SEARCHENGINESPECIFICS
  
  # @@protoc_insertion_point(class_scope:sync_pb.SearchEngineSpecifics)

search_engine.message_type = _SEARCHENGINESPECIFICS
sync_pb2.EntitySpecifics.RegisterExtension(search_engine)
# @@protoc_insertion_point(module_scope)
