# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='sync_enums.proto',
  package='sync_pb',
  serialized_pb='\n\x10sync_enums.proto\x12\x07sync_pb\"\xcc\x03\n\tSyncEnums\"\xe7\x01\n\tEventType\x12\x0e\n\nAUTH_ERROR\x10\x01\x12\x11\n\rUPDATED_TOKEN\x10\x02\x12\x17\n\x13PASSPHRASE_REQUIRED\x10\x03\x12\x17\n\x13PASSPHRASE_ACCEPTED\x10\x04\x12\x1b\n\x17INITIALIZATION_COMPLETE\x10\x05\x12\x1c\n\x18STOP_SYNCING_PERMANENTLY\x10\x06\x12\x1b\n\x17\x45NCRYPTED_TYPES_CHANGED\x10\t\x12\x17\n\x13\x45NCRYPTION_COMPLETE\x10\x07\x12\x14\n\x10\x41\x43TIONABLE_ERROR\x10\x08\"\xd4\x01\n\tErrorType\x12\x0b\n\x07SUCCESS\x10\x00\x12\x11\n\rACCESS_DENIED\x10\x01\x12\x13\n\x0fNOT_MY_BIRTHDAY\x10\x02\x12\r\n\tTHROTTLED\x10\x03\x12\x10\n\x0c\x41UTH_EXPIRED\x10\x04\x12\x16\n\x12USER_NOT_ACTIVATED\x10\x05\x12\x10\n\x0c\x41UTH_INVALID\x10\x06\x12\x11\n\rCLEAR_PENDING\x10\x07\x12\x13\n\x0fTRANSIENT_ERROR\x10\x08\x12\x12\n\x0eMIGRATION_DONE\x10\t\x12\x0b\n\x07UNKNOWN\x10\x64\x42\x04H\x03X\x01')



_SYNCENUMS_EVENTTYPE = descriptor.EnumDescriptor(
  name='EventType',
  full_name='sync_pb.SyncEnums.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='AUTH_ERROR', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UPDATED_TOKEN', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PASSPHRASE_REQUIRED', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PASSPHRASE_ACCEPTED', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INITIALIZATION_COMPLETE', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STOP_SYNCING_PERMANENTLY', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ENCRYPTED_TYPES_CHANGED', index=6, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ENCRYPTION_COMPLETE', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIONABLE_ERROR', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=44,
  serialized_end=275,
)

_SYNCENUMS_ERRORTYPE = descriptor.EnumDescriptor(
  name='ErrorType',
  full_name='sync_pb.SyncEnums.ErrorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACCESS_DENIED', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NOT_MY_BIRTHDAY', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='THROTTLED', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AUTH_EXPIRED', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='USER_NOT_ACTIVATED', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AUTH_INVALID', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CLEAR_PENDING', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TRANSIENT_ERROR', index=8, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MIGRATION_DONE', index=9, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=10, number=100,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=278,
  serialized_end=490,
)


_SYNCENUMS = descriptor.Descriptor(
  name='SyncEnums',
  full_name='sync_pb.SyncEnums',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SYNCENUMS_EVENTTYPE,
    _SYNCENUMS_ERRORTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=490,
)

_SYNCENUMS_EVENTTYPE.containing_type = _SYNCENUMS;
_SYNCENUMS_ERRORTYPE.containing_type = _SYNCENUMS;
DESCRIPTOR.message_types_by_name['SyncEnums'] = _SYNCENUMS

class SyncEnums(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SYNCENUMS
  
  # @@protoc_insertion_point(class_scope:sync_pb.SyncEnums)

# @@protoc_insertion_point(module_scope)
