# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import sync_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='typed_url_specifics.proto',
  package='sync_pb',
  serialized_pb='\n\x19typed_url_specifics.proto\x12\x07sync_pb\x1a\nsync.proto\"r\n\x11TypedUrlSpecifics\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06hidden\x18\x04 \x01(\x08\x12\x12\n\x06visits\x18\x07 \x03(\x03\x42\x02\x10\x01\x12\x1d\n\x11visit_transitions\x18\x08 \x03(\x05\x42\x02\x10\x01:I\n\ttyped_url\x12\x18.sync_pb.EntitySpecifics\x18\xcd\xbe\x02 \x01(\x0b\x32\x1a.sync_pb.TypedUrlSpecificsB\x04H\x03X\x01')


TYPED_URL_FIELD_NUMBER = 40781
typed_url = descriptor.FieldDescriptor(
  name='typed_url', full_name='sync_pb.typed_url', index=0,
  number=40781, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_TYPEDURLSPECIFICS = descriptor.Descriptor(
  name='TypedUrlSpecifics',
  full_name='sync_pb.TypedUrlSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='url', full_name='sync_pb.TypedUrlSpecifics.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='title', full_name='sync_pb.TypedUrlSpecifics.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hidden', full_name='sync_pb.TypedUrlSpecifics.hidden', index=2,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='visits', full_name='sync_pb.TypedUrlSpecifics.visits', index=3,
      number=7, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    descriptor.FieldDescriptor(
      name='visit_transitions', full_name='sync_pb.TypedUrlSpecifics.visit_transitions', index=4,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=50,
  serialized_end=164,
)

DESCRIPTOR.message_types_by_name['TypedUrlSpecifics'] = _TYPEDURLSPECIFICS

class TypedUrlSpecifics(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TYPEDURLSPECIFICS
  
  # @@protoc_insertion_point(class_scope:sync_pb.TypedUrlSpecifics)

typed_url.message_type = _TYPEDURLSPECIFICS
sync_pb2.EntitySpecifics.RegisterExtension(typed_url)
# @@protoc_insertion_point(module_scope)
