# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='control.proto',
  package='remoting.protocol',
  serialized_pb='\n\rcontrol.proto\x12\x11remoting.protocol\"-\n\x1aLocalLoginStatusDeprecated\x12\x0f\n\x07success\x18\x01 \x01(\x08\"]\n\x16\x42\x65ginSessionDeprecated\x12\x43\n\x0clogin_status\x18\x01 \x01(\x0b\x32-.remoting.protocol.LocalLoginStatusDeprecatedB\x02H\x03')




_LOCALLOGINSTATUSDEPRECATED = descriptor.Descriptor(
  name='LocalLoginStatusDeprecated',
  full_name='remoting.protocol.LocalLoginStatusDeprecated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='success', full_name='remoting.protocol.LocalLoginStatusDeprecated.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=81,
)


_BEGINSESSIONDEPRECATED = descriptor.Descriptor(
  name='BeginSessionDeprecated',
  full_name='remoting.protocol.BeginSessionDeprecated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='login_status', full_name='remoting.protocol.BeginSessionDeprecated.login_status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=83,
  serialized_end=176,
)

_BEGINSESSIONDEPRECATED.fields_by_name['login_status'].message_type = _LOCALLOGINSTATUSDEPRECATED
DESCRIPTOR.message_types_by_name['LocalLoginStatusDeprecated'] = _LOCALLOGINSTATUSDEPRECATED
DESCRIPTOR.message_types_by_name['BeginSessionDeprecated'] = _BEGINSESSIONDEPRECATED

class LocalLoginStatusDeprecated(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOCALLOGINSTATUSDEPRECATED
  
  # @@protoc_insertion_point(class_scope:remoting.protocol.LocalLoginStatusDeprecated)

class BeginSessionDeprecated(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BEGINSESSIONDEPRECATED
  
  # @@protoc_insertion_point(class_scope:remoting.protocol.BeginSessionDeprecated)

# @@protoc_insertion_point(module_scope)
