# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='event.proto',
  package='remoting.protocol',
  serialized_pb='\n\x0b\x65vent.proto\x12\x11remoting.protocol\",\n\x08KeyEvent\x12\x0f\n\x07keycode\x18\x01 \x02(\x05\x12\x0f\n\x07pressed\x18\x02 \x02(\x08\"\x8d\x02\n\nMouseEvent\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\x16\n\x0ewheel_offset_x\x18\x03 \x01(\x05\x12\x16\n\x0ewheel_offset_y\x18\x04 \x01(\x05\x12\x39\n\x06\x62utton\x18\x05 \x01(\x0e\x32).remoting.protocol.MouseEvent.MouseButton\x12\x13\n\x0b\x62utton_down\x18\x06 \x01(\x08\"i\n\x0bMouseButton\x12\x14\n\x10\x42UTTON_UNDEFINED\x10\x00\x12\x0f\n\x0b\x42UTTON_LEFT\x10\x01\x12\x11\n\rBUTTON_MIDDLE\x10\x02\x12\x10\n\x0c\x42UTTON_RIGHT\x10\x03\x12\x0e\n\nBUTTON_MAX\x10\x04\x42\x02H\x03')



_MOUSEEVENT_MOUSEBUTTON = descriptor.EnumDescriptor(
  name='MouseButton',
  full_name='remoting.protocol.MouseEvent.MouseButton',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='BUTTON_UNDEFINED', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BUTTON_LEFT', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BUTTON_MIDDLE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BUTTON_RIGHT', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BUTTON_MAX', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=245,
  serialized_end=350,
)


_KEYEVENT = descriptor.Descriptor(
  name='KeyEvent',
  full_name='remoting.protocol.KeyEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='keycode', full_name='remoting.protocol.KeyEvent.keycode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pressed', full_name='remoting.protocol.KeyEvent.pressed', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=78,
)


_MOUSEEVENT = descriptor.Descriptor(
  name='MouseEvent',
  full_name='remoting.protocol.MouseEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x', full_name='remoting.protocol.MouseEvent.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='remoting.protocol.MouseEvent.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wheel_offset_x', full_name='remoting.protocol.MouseEvent.wheel_offset_x', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wheel_offset_y', full_name='remoting.protocol.MouseEvent.wheel_offset_y', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='button', full_name='remoting.protocol.MouseEvent.button', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='button_down', full_name='remoting.protocol.MouseEvent.button_down', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MOUSEEVENT_MOUSEBUTTON,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=81,
  serialized_end=350,
)

_MOUSEEVENT.fields_by_name['button'].enum_type = _MOUSEEVENT_MOUSEBUTTON
_MOUSEEVENT_MOUSEBUTTON.containing_type = _MOUSEEVENT;
DESCRIPTOR.message_types_by_name['KeyEvent'] = _KEYEVENT
DESCRIPTOR.message_types_by_name['MouseEvent'] = _MOUSEEVENT

class KeyEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _KEYEVENT
  
  # @@protoc_insertion_point(class_scope:remoting.protocol.KeyEvent)

class MouseEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MOUSEEVENT
  
  # @@protoc_insertion_point(class_scope:remoting.protocol.MouseEvent)

# @@protoc_insertion_point(module_scope)
