# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='trace.proto',
  package='remoting',
  serialized_pb='\n\x0btrace.proto\x12\x08remoting\"u\n\x0bTraceRecord\x12\x12\n\nannotation\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x02(\x03\x12\x15\n\tsource_id\x18\x03 \x01(\x03:\x02-1\x12\x11\n\tthread_id\x18\x04 \x01(\x06\x12\x15\n\nclock_skew\x18\x05 \x01(\x03:\x01\x30\"B\n\x0bTraceBuffer\x12\x0c\n\x04name\x18\x01 \x02(\t\x12%\n\x06record\x18\x02 \x03(\x0b\x32\x15.remoting.TraceRecordB\x02H\x03')




_TRACERECORD = descriptor.Descriptor(
  name='TraceRecord',
  full_name='remoting.TraceRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='annotation', full_name='remoting.TraceRecord.annotation', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='remoting.TraceRecord.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='source_id', full_name='remoting.TraceRecord.source_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='thread_id', full_name='remoting.TraceRecord.thread_id', index=3,
      number=4, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='clock_skew', full_name='remoting.TraceRecord.clock_skew', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=142,
)


_TRACEBUFFER = descriptor.Descriptor(
  name='TraceBuffer',
  full_name='remoting.TraceBuffer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='remoting.TraceBuffer.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='record', full_name='remoting.TraceBuffer.record', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=144,
  serialized_end=210,
)

_TRACEBUFFER.fields_by_name['record'].message_type = _TRACERECORD
DESCRIPTOR.message_types_by_name['TraceRecord'] = _TRACERECORD
DESCRIPTOR.message_types_by_name['TraceBuffer'] = _TRACEBUFFER

class TraceRecord(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRACERECORD
  
  # @@protoc_insertion_point(class_scope:remoting.TraceRecord)

class TraceBuffer(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRACEBUFFER
  
  # @@protoc_insertion_point(class_scope:remoting.TraceBuffer)

# @@protoc_insertion_point(module_scope)
