# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='video.proto',
  package='remoting',
  serialized_pb='\n\x0bvideo.proto\x12\x08remoting\"\xa6\x02\n\x11VideoPacketFormat\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12H\n\x08\x65ncoding\x18\x05 \x01(\x0e\x32$.remoting.VideoPacketFormat.Encoding:\x10\x45NCODING_INVALID\x12\x14\n\x0cscreen_width\x18\x06 \x01(\x05\x12\x15\n\rscreen_height\x18\x07 \x01(\x05\"e\n\x08\x45ncoding\x12\x1d\n\x10\x45NCODING_INVALID\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x15\n\x11\x45NCODING_VERBATIM\x10\x00\x12\x11\n\rENCODING_ZLIB\x10\x01\x12\x10\n\x0c\x45NCODING_VP8\x10\x02\";\n\x04Rect\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"\xc2\x02\n\x0bVideoPacket\x12\x10\n\x05\x66lags\x18\x01 \x01(\x05:\x01\x30\x12\x1a\n\x0fsequence_number\x18\x02 \x01(\x05:\x01\x30\x12\x14\n\ttimestamp\x18\x03 \x01(\x05:\x01\x30\x12+\n\x06\x66ormat\x18\x04 \x01(\x0b\x32\x1b.remoting.VideoPacketFormat\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12#\n\x0b\x64irty_rects\x18\x06 \x03(\x0b\x32\x0e.remoting.Rect\x12\x17\n\x0f\x63\x61pture_time_ms\x18\x07 \x01(\x05\x12\x16\n\x0e\x65ncode_time_ms\x18\x08 \x01(\x05\x12\x1e\n\x16\x63lient_sequence_number\x18\t \x01(\x03\">\n\x05\x46lags\x12\x10\n\x0c\x46IRST_PACKET\x10\x01\x12\x0f\n\x0bLAST_PACKET\x10\x02\x12\x12\n\x0eLAST_PARTITION\x10\x04\x42\x02H\x03')



_VIDEOPACKETFORMAT_ENCODING = descriptor.EnumDescriptor(
  name='Encoding',
  full_name='remoting.VideoPacketFormat.Encoding',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='ENCODING_INVALID', index=0, number=-1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ENCODING_VERBATIM', index=1, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ENCODING_ZLIB', index=2, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ENCODING_VP8', index=3, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=219,
  serialized_end=320,
)

_VIDEOPACKET_FLAGS = descriptor.EnumDescriptor(
  name='Flags',
  full_name='remoting.VideoPacket.Flags',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='FIRST_PACKET', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LAST_PACKET', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LAST_PARTITION', index=2, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=644,
  serialized_end=706,
)


_VIDEOPACKETFORMAT = descriptor.Descriptor(
  name='VideoPacketFormat',
  full_name='remoting.VideoPacketFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x', full_name='remoting.VideoPacketFormat.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='remoting.VideoPacketFormat.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='width', full_name='remoting.VideoPacketFormat.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='height', full_name='remoting.VideoPacketFormat.height', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='encoding', full_name='remoting.VideoPacketFormat.encoding', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='screen_width', full_name='remoting.VideoPacketFormat.screen_width', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='screen_height', full_name='remoting.VideoPacketFormat.screen_height', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VIDEOPACKETFORMAT_ENCODING,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=320,
)


_RECT = descriptor.Descriptor(
  name='Rect',
  full_name='remoting.Rect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x', full_name='remoting.Rect.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='remoting.Rect.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='width', full_name='remoting.Rect.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='height', full_name='remoting.Rect.height', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=322,
  serialized_end=381,
)


_VIDEOPACKET = descriptor.Descriptor(
  name='VideoPacket',
  full_name='remoting.VideoPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='flags', full_name='remoting.VideoPacket.flags', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sequence_number', full_name='remoting.VideoPacket.sequence_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='remoting.VideoPacket.timestamp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='format', full_name='remoting.VideoPacket.format', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='remoting.VideoPacket.data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dirty_rects', full_name='remoting.VideoPacket.dirty_rects', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='capture_time_ms', full_name='remoting.VideoPacket.capture_time_ms', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='encode_time_ms', full_name='remoting.VideoPacket.encode_time_ms', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='client_sequence_number', full_name='remoting.VideoPacket.client_sequence_number', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VIDEOPACKET_FLAGS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=384,
  serialized_end=706,
)

_VIDEOPACKETFORMAT.fields_by_name['encoding'].enum_type = _VIDEOPACKETFORMAT_ENCODING
_VIDEOPACKETFORMAT_ENCODING.containing_type = _VIDEOPACKETFORMAT;
_VIDEOPACKET.fields_by_name['format'].message_type = _VIDEOPACKETFORMAT
_VIDEOPACKET.fields_by_name['dirty_rects'].message_type = _RECT
_VIDEOPACKET_FLAGS.containing_type = _VIDEOPACKET;
DESCRIPTOR.message_types_by_name['VideoPacketFormat'] = _VIDEOPACKETFORMAT
DESCRIPTOR.message_types_by_name['Rect'] = _RECT
DESCRIPTOR.message_types_by_name['VideoPacket'] = _VIDEOPACKET

class VideoPacketFormat(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VIDEOPACKETFORMAT
  
  # @@protoc_insertion_point(class_scope:remoting.VideoPacketFormat)

class Rect(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RECT
  
  # @@protoc_insertion_point(class_scope:remoting.Rect)

class VideoPacket(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VIDEOPACKET
  
  # @@protoc_insertion_point(class_scope:remoting.VideoPacket)

# @@protoc_insertion_point(module_scope)
