Import('build_env')
import os, sys

Import ('debug')
Import ('x64')
Import ('componentName')
Import ('suffixName')

## Add Tests folders here
# Temp using absolute paths
include_dirs = [
  '.',
  '../../include',
  '../../src/sipcc/include',
  '../../src/common',
  '../../out/include/system',
  '../../third_party/chromium_base',
  '../../src/common/browser_logging'
]

## Add test src files here
#
src_files = Glob('*.cpp')
libpath = ['../../out/lib']
libs = []

env = build_env.Clone(CPPPATH=include_dirs)

if sys.platform =='win32':
  env["CPPDEFINES"] += [
    'WIN32',
    '_CONSOLE',
    'MBCS'
  ]
  env["CPPFLAGS"] += [
    '/c',
    '/TP',
    '/W4',
    '/wd4100',
    '/wd4275',
    '/wd4512'
  ]
  windows_sdk_lib_dir=os.environ['MS_WINDOWS_SDK_PATH'] + '/lib'
  ms_vc_lib_dir=os.environ['MS_VC_PATH'] + '/VC/lib'
  ms_vc_atlmfc_lib_dir=os.environ['MS_VC_PATH'] + '/VC/ATLMFC/lib'
  libpath += [ 
    ms_vc_lib_dir,
    windows_sdk_lib_dir,
    ms_vc_atlmfc_lib_dir,
    '../../third_party/lib',
    '../../third_party/chromium_base',
    '../../src/common/browser_logging'
  ]
  libs += [
    componentName + suffixName + '.lib',
    'winmm.lib',
    'kernel32.lib',
    'user32.lib',
    'gdi32.lib',
    'winspool.lib',
    'comdlg32.lib',
    'advapi32.lib',
    'shell32.lib',
    'ole32.lib',
    'oleaut32.lib',
    'uuid.lib',
    'odbc32.lib',
    'odbccp32.lib', 
    'atls.lib',  
    'avrt.lib', 
    'DelayImp.lib', 
    'ddraw.lib', 
    'ws2_32.lib', 
    'mswsock.lib', 
    'dbghelp.lib', 
    'Psapi.lib',
    'chromium.lib',
    'browser_logging.lib',
    'GIPSVideoEngineWindows_MT.lib'
  ]
  if int(debug):
    libs += [
      'libcmtd.lib',
      'libcurl_mtd.lib',
      'libxml2_mtd.lib',
      'libeay32_mtd.lib',
      'ssleay32_mtd.lib'
    ]
  else:
    libs += [
      'libcmt.lib',
      'libcurl_mt.lib'
      'libxml2_mt.lib',
      'libeay32_mt.lib',
      'ssleay32_mt.lib'
    ]
  env["LINKFLAGS"] = [
    '/DELAYLOAD:"avrt.dll"',
    '/SUBSYSTEM:CONSOLE',
    '/DYNAMICBASE',
    '/NXCOMPAT',
    '/MACHINE:X86',
    '/FORCE:MULTIPLE',
    '/NODEFAULTLIB:"libcmtd.lib"',
    '/NODEFAULTLIB:"libcmt.lib"',
    '/NODEFAULTLIB:"libmmt.lib"',
    '/NODEFAULTLIB:"libcpmt.lib"',
    '/NODEFAULTLIB:"avrt.lib"',
    '/NODEFAULTLIB:"libirc.lib"',
    '/NODEFAULTLIB:"advapi32.lib"'
  ]
  if int(debug):
    env["LINKFLAGS"] += [
      '/DEBUG '
     ]
elif sys.platform == 'darwin':
  env["CPPFLAGS"] += [
    '-W'
  ]
  libpath += [
    '../..',
    '../../third_party/chromium_base',
    '../../third_party/lib',
  ]
  libs += [
    componentName + suffixName,
    'ssl',
    'crypto',
    'apr-1',
    'aprutil-1',
    'z',
    'curl', 
    'libxml2', 
    'iconv',
    'X11',
    'chromium',
    'VideoEngine_mac_intel_gcc.a' 
  ]
  env["LINKFLAGS"] += [
    '-framework',
    'CoreAudio',
    '-framework',
    'AudioToolbox',
    '-framework',
    'CoreServices',
    '-framework',
    'IOKit'
  ]
elif sys.platform=='linux2':
  libpath += [
    '../../third_party/chromium_base',
    '../../third_party/lib',
    '/usr/lib'
  ]
  libs += [
    componentName + suffixName, 
    'pthread',
    'z', 
    'idn', 
    'dl', 
    'rt',
    'curl',
    'xml2', 
    'asound',
    'Xext',
    'glib-2.0',
    'chromium',
    'VideoEngine_Linux_gcc'
  ]
  env["LINKFLAGS"] += [
    '-z',
    'muldefs'
  ]
  
  
buildResult = env.Program('TestApp_SoftPhone', src_files,
  LIBS=libs,
  LIBPATH=libpath)


if sys.platform =='win32':
  Depends(buildResult, '../../' + componentName + suffixName + '.lib')
else:
  Depends(buildResult, '../../lib' + componentName + suffixName + '.a')


