Import('build_env')
import os, sys

Import ('debug')
Import ('x64')
Import ('componentName')
Import ('suffixName')
Import('webrtcpath')


## Add Tests folders here
# Temp using absolute paths
include_dirs = [
  '.',
  '../../include',
  '../../src/sipcc/include',
  '../../src/common',
  '../../out/include/system',
  '../../third_party/chromium_base',
  '../../src/common/browser_logging'
]

## Add test src files here
#
src_files = Glob('*.cpp')
libpath = ['../../out/lib']
libs = []

env = build_env.Clone(CPPPATH=include_dirs)

if sys.platform =='win32':
  env["CPPDEFINES"] += [
    'WIN32',
    '_CONSOLE',
    'MBCS'
  ]
  env["CPPFLAGS"] += [
    '/c',
    '/TP',
    '/W4',
    '/wd4100',
    '/wd4275',
    '/wd4512'
  ]
  windows_sdk_lib_dir=os.environ['MS_WINDOWS_SDK_PATH'] + '/lib'
  ms_vc_lib_dir=os.environ['MS_VC_PATH'] + '/VC/lib'
  ms_vc_atlmfc_lib_dir=os.environ['MS_VC_PATH'] + '/VC/ATLMFC/lib'
  libpath += [ 
    ms_vc_lib_dir,
    windows_sdk_lib_dir,
    ms_vc_atlmfc_lib_dir,
    '../../third_party/lib',
    '../../third_party/chromium_base',
    '../../src/common/browser_logging'
  ]
  libs += [
    componentName + suffixName + '.lib',
    'winmm.lib',
    'kernel32.lib',
    'user32.lib',
    'gdi32.lib',
    'winspool.lib',
    'comdlg32.lib',
    'advapi32.lib',
    'shell32.lib',
    'ole32.lib',
    'oleaut32.lib',
    'uuid.lib',
    'odbc32.lib',
    'odbccp32.lib', 
    'atls.lib',  
    'avrt.lib', 
    'DelayImp.lib', 
    'ddraw.lib', 
    'ws2_32.lib', 
    'mswsock.lib', 
    'dbghelp.lib', 
    'Psapi.lib',
    'chromium.lib',
    'browser_logging.lib',
    'GIPSVideoEngineWindows_MT.lib'
  ]
  if int(debug):
    libs += [
      'libcmtd.lib',
      'libxml2_mtd.lib'
    ]
  else:
    libs += [
      'libcmt.lib',
      'libxml2_mt.lib'
    ]
  env["LINKFLAGS"] = [
    '/DELAYLOAD:"avrt.dll"',
    '/SUBSYSTEM:CONSOLE',
    '/DYNAMICBASE',
    '/NXCOMPAT',
    '/MACHINE:X86',
    '/FORCE:MULTIPLE',
    '/NODEFAULTLIB:"libcmtd.lib"',
    '/NODEFAULTLIB:"libcmt.lib"',
    '/NODEFAULTLIB:"libmmt.lib"',
    '/NODEFAULTLIB:"libcpmt.lib"',
    '/NODEFAULTLIB:"avrt.lib"',
    '/NODEFAULTLIB:"libirc.lib"',
    '/NODEFAULTLIB:"advapi32.lib"'
  ]
  if int(debug):
    env["LINKFLAGS"] += [
      '/DEBUG '
     ]
elif sys.platform == 'darwin':
  env["CPPFLAGS"] += [
    '-W',
  ]
  libpath += [
    '../..',
    '../../third_party/chromium_base',
    '../../third_party/lib',
    webrtcpath + '/xcodebuild/Debug',
  ]
  libs += [
    componentName + suffixName,
    'ssl',
    'crypto',
    'apr-1',
    'aprutil-1',
    'z',
    'libxml2', 
    'iconv',
    'X11',
    'chromium',
    'libaec.a',
    'libaecm.a',
	'libagc.a',
    'libapm_util.a',
    'libaudio_coding_module.a',
    'libaudio_conference_mixer.a',
    'libaudio_device.a',
    'libaudio_processing.a',
    'libCNG.a',
    'libG711.a',
    'libG722.a',
    'libgenperf_libs.a',
    'libiLBC.a',
    'libiSAC.a',
    'libiSACFix.a',
    'libjpeg_turbo.a',
    'libmedia_file.a',
    'libNetEq.a',
    'libns.a',
    'libPCM16B.a',
    'libresampler.a',
    'librtp_rtcp.a',
    'libspl.a',
    'libprotobuf_lite.a',
	'libsystem_wrappers.a',
    'libudp_transport.a',
	'libvad.a',
    'libvideo_capture_module.a',
    'libvideo_engine_core.a',
    'libvideo_processing.a',
	'libvideo_render_module.a',
	'libvoice_engine_core.a',
	'libvpx.a',
	'libwebrtc_i420.a',
	'libwebrtc_jpeg.a',
	'libwebrtc_utility.a',
	'libwebrtc_video_coding.a',
	'libwebrtc_vp8.a',
	'libwebrtc_vplib.a'
  ]
  env["LINKFLAGS"] += [
    '-framework',
    'CoreAudio',
    '-framework',
    'AudioToolbox',
    '-framework',
    'CoreServices',
    '-framework',
    'IOKit'
  ]
elif sys.platform=='linux2':
  libpath += [
    '../../third_party/chromium_base',
    '../../third_party/lib',
    '/usr/lib',
     webrtcpath + '/out/Debug/obj.target/src/video_engine/main/source',
     webrtcpath + '/out/Debug/obj.target/src/voice_engine/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/video_render/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/media_file/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/video_processing/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/video_capture/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/utility/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/video_coding/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/video_coding/codecs/vp8/main/source',
     webrtcpath + '/out/Debug/obj.target/src/common_video/jpeg/main/source',
     webrtcpath + '/out/Debug/obj.target/third_party/libvpx',
     webrtcpath + '/out/Debug/obj.target/third_party/libjpeg_turbo',
     webrtcpath + '/out/Debug/obj.target/src/modules/audio_coding/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/audio_processing/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/audio_device/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/audio_coding/NetEQ/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/audio_processing/ns/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/audio_processing/aecm/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/audio_processing/aec/main/source',
     webrtcpath + '/out/Debug/obj.target/src/common_audio/resampler/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/audio_coding/codecs/iLBC/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/audio_processing/agc/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/audio_coding/codecs/CNG/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/audio_coding/codecs/iSAC/fix/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/audio_coding/codecs/iSAC/main/source',
     webrtcpath + '/out/Debug/obj.target/src/common_audio/vad/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/udp_transport/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/audio_conference_mixer/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/rtp_rtcp/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/video_coding/codecs/i420/main/source',
     webrtcpath + '/out/Debug/obj.target/src/common_video/vplib/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/audio_coding/codecs/G711/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/audio_processing/utility',
     webrtcpath + '/out/Debug/obj.target/src/common_audio/signal_processing_library/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/audio_coding/codecs/G722/main/source',
     webrtcpath + '/out/Debug/obj.target/src/modules/audio_coding/codecs/PCM16B/main/source',
     webrtcpath + '/out/Debug/obj.target/third_party/protobuf',
     webrtcpath + '/out/Debug/obj.target/src/system_wrappers/source'
  ]
  libs += [
    componentName + suffixName, 
    'pthread',
    'z', 
    'idn', 
    'dl', 
    'rt',
    'xml2', 
    'asound',
    'Xext',
    'glib-2.0',
    'chromium',
    'libvideo_engine_core.a',
    'libvoice_engine_core.a',
    'libvideo_render_module.a',
    'libmedia_file.a',
    'libvideo_processing.a',
    'libvideo_capture_module.a',
    'libwebrtc_utility.a',
    'libwebrtc_video_coding.a',
    'libwebrtc_vp8.a',
    'libwebrtc_jpeg.a',
    'libvpx.a',
    'libjpeg_turbo.a',
    'libaudio_coding_module.a',
    'libaudio_processing.a',
    'libaudio_device.a',
    'libNetEq.a',
    'libns.a',
    'libaecm.a',
    'libaec.a',
    'libresampler.a',
    'libiLBC.a',
    'libagc.a',
    'libCNG.a',
    'libiSACFix.a',
    'libiSAC.a',
    'libvad.a',
    'libudp_transport.a',
    'libaudio_conference_mixer.a',
    'librtp_rtcp.a',
    'libwebrtc_i420.a',
    'libwebrtc_vplib.a',
    'libG711.a',
    'libapm_util.a',
    'libspl.a',
    'libG722.a',
    'libPCM16B.a',
    'libprotobuf_lite.a',
    'libsystem_wrappers.a'
  ]
  env["LINKFLAGS"] += [
    '-z',
    'muldefs'
  ]
  
  
buildResult = env.Program('TestApp_SoftPhone', src_files,
  LIBS=libs,
  LIBPATH=libpath)


if sys.platform =='win32':
  Depends(buildResult, '../../' + componentName + suffixName + '.lib')
else:
  Depends(buildResult, '../../lib' + componentName + suffixName + '.a')


