
import os
import sys

Import('build_env')
Import('debug')
Import('mozsrcpath')
Import('x64')

include_dirs = [
  '.',
  'include',
  '../../../third_party/chromium_base',
  mozsrcpath + '/ipc/chromium/src'
]

src_files = Glob('*.cpp')


env = build_env.Clone(CPPPATH=include_dirs)

env.Library('browser_logging', src_files)


