
import os
import sys

Import('build_env')
Import('debug')
Import('mozsrcpath')
Import('x64')
Import('chromiumbaseincludepath')

if(chromiumbaseincludepath == 'third_party'):
  chromiumbaseincludepath = '../../../third_party/chromium_base'

include_dirs = [
  '.',
  'include',
  chromiumbaseincludepath
]

src_files = Glob('*.cpp')


env = build_env.Clone(CPPPATH=include_dirs)

env.Library('browser_logging', src_files)


