# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='old_generic_format.proto',
  package='enterprise_management',
  serialized_pb='\n\x18old_generic_format.proto\x12\x15\x65nterprise_management\"O\n\x0eGenericSetting\x12=\n\x0bnamed_value\x18\x01 \x03(\x0b\x32(.enterprise_management.GenericNamedValue\"\x91\x04\n\x0cGenericValue\x12T\n\nvalue_type\x18\x01 \x01(\x0e\x32-.enterprise_management.GenericValue.ValueType:\x11VALUE_TYPE_STRING\x12\x12\n\nbool_value\x18\x02 \x01(\x08\x12\x13\n\x0bint64_value\x18\x03 \x01(\x03\x12\x14\n\x0cstring_value\x18\x04 \x01(\t\x12\x14\n\x0c\x64ouble_value\x18\x05 \x01(\x01\x12\x13\n\x0b\x62ytes_value\x18\x06 \x01(\x0c\x12\x12\n\nbool_array\x18\x07 \x03(\x08\x12\x13\n\x0bint64_array\x18\x08 \x03(\x03\x12\x14\n\x0cstring_array\x18\t \x03(\t\x12\x14\n\x0c\x64ouble_array\x18\n \x03(\x01\"\xeb\x01\n\tValueType\x12\x13\n\x0fVALUE_TYPE_BOOL\x10\x01\x12\x14\n\x10VALUE_TYPE_INT64\x10\x02\x12\x15\n\x11VALUE_TYPE_STRING\x10\x03\x12\x15\n\x11VALUE_TYPE_DOUBLE\x10\x04\x12\x14\n\x10VALUE_TYPE_BYTES\x10\x05\x12\x19\n\x15VALUE_TYPE_BOOL_ARRAY\x10\x06\x12\x1a\n\x16VALUE_TYPE_INT64_ARRAY\x10\x07\x12\x1b\n\x17VALUE_TYPE_STRING_ARRAY\x10\x08\x12\x1b\n\x17VALUE_TYPE_DOUBLE_ARRAY\x10\t\"U\n\x11GenericNamedValue\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x32\n\x05value\x18\x02 \x01(\x0b\x32#.enterprise_management.GenericValue\"Z\n\x19LegacyChromeSettingsProto\x12=\n\x0bnamed_value\x18\x02 \x03(\x0b\x32(.enterprise_management.GenericNamedValueB\x02H\x03')



_GENERICVALUE_VALUETYPE = descriptor.EnumDescriptor(
  name='ValueType',
  full_name='enterprise_management.GenericValue.ValueType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='VALUE_TYPE_BOOL', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VALUE_TYPE_INT64', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VALUE_TYPE_STRING', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VALUE_TYPE_DOUBLE', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VALUE_TYPE_BYTES', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VALUE_TYPE_BOOL_ARRAY', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VALUE_TYPE_INT64_ARRAY', index=6, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VALUE_TYPE_STRING_ARRAY', index=7, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VALUE_TYPE_DOUBLE_ARRAY', index=8, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=427,
  serialized_end=662,
)


_GENERICSETTING = descriptor.Descriptor(
  name='GenericSetting',
  full_name='enterprise_management.GenericSetting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='named_value', full_name='enterprise_management.GenericSetting.named_value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=51,
  serialized_end=130,
)


_GENERICVALUE = descriptor.Descriptor(
  name='GenericValue',
  full_name='enterprise_management.GenericValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value_type', full_name='enterprise_management.GenericValue.value_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bool_value', full_name='enterprise_management.GenericValue.bool_value', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='int64_value', full_name='enterprise_management.GenericValue.int64_value', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='string_value', full_name='enterprise_management.GenericValue.string_value', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='double_value', full_name='enterprise_management.GenericValue.double_value', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bytes_value', full_name='enterprise_management.GenericValue.bytes_value', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bool_array', full_name='enterprise_management.GenericValue.bool_array', index=6,
      number=7, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='int64_array', full_name='enterprise_management.GenericValue.int64_array', index=7,
      number=8, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='string_array', full_name='enterprise_management.GenericValue.string_array', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='double_array', full_name='enterprise_management.GenericValue.double_array', index=9,
      number=10, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GENERICVALUE_VALUETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=133,
  serialized_end=662,
)


_GENERICNAMEDVALUE = descriptor.Descriptor(
  name='GenericNamedValue',
  full_name='enterprise_management.GenericNamedValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='enterprise_management.GenericNamedValue.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='enterprise_management.GenericNamedValue.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=664,
  serialized_end=749,
)


_LEGACYCHROMESETTINGSPROTO = descriptor.Descriptor(
  name='LegacyChromeSettingsProto',
  full_name='enterprise_management.LegacyChromeSettingsProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='named_value', full_name='enterprise_management.LegacyChromeSettingsProto.named_value', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=751,
  serialized_end=841,
)

_GENERICSETTING.fields_by_name['named_value'].message_type = _GENERICNAMEDVALUE
_GENERICVALUE.fields_by_name['value_type'].enum_type = _GENERICVALUE_VALUETYPE
_GENERICVALUE_VALUETYPE.containing_type = _GENERICVALUE;
_GENERICNAMEDVALUE.fields_by_name['value'].message_type = _GENERICVALUE
_LEGACYCHROMESETTINGSPROTO.fields_by_name['named_value'].message_type = _GENERICNAMEDVALUE
DESCRIPTOR.message_types_by_name['GenericSetting'] = _GENERICSETTING
DESCRIPTOR.message_types_by_name['GenericValue'] = _GENERICVALUE
DESCRIPTOR.message_types_by_name['GenericNamedValue'] = _GENERICNAMEDVALUE
DESCRIPTOR.message_types_by_name['LegacyChromeSettingsProto'] = _LEGACYCHROMESETTINGSPROTO

class GenericSetting(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GENERICSETTING
  
  # @@protoc_insertion_point(class_scope:enterprise_management.GenericSetting)

class GenericValue(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GENERICVALUE
  
  # @@protoc_insertion_point(class_scope:enterprise_management.GenericValue)

class GenericNamedValue(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GENERICNAMEDVALUE
  
  # @@protoc_insertion_point(class_scope:enterprise_management.GenericNamedValue)

class LegacyChromeSettingsProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LEGACYCHROMESETTINGSPROTO
  
  # @@protoc_insertion_point(class_scope:enterprise_management.LegacyChromeSettingsProto)

# @@protoc_insertion_point(module_scope)
