# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import math_pb2
import dom_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='annotations.proto',
  package='userfeedback',
  serialized_pb='\n\x11\x61nnotations.proto\x12\x0cuserfeedback\x1a\nmath.proto\x1a\tdom.proto\"\x7f\n\nAnnotation\x12*\n\trectangle\x18\x01 \x02(\x0b\x32\x17.userfeedback.Rectangle\x12\x0f\n\x07snippet\x18\x02 \x01(\t\x12\x34\n\x14\x61nnotatedElementPath\x18\x03 \x01(\x0b\x32\x16.userfeedback.HtmlPathB\x02H\x03')




_ANNOTATION = descriptor.Descriptor(
  name='Annotation',
  full_name='userfeedback.Annotation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='rectangle', full_name='userfeedback.Annotation.rectangle', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='snippet', full_name='userfeedback.Annotation.snippet', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='annotatedElementPath', full_name='userfeedback.Annotation.annotatedElementPath', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=58,
  serialized_end=185,
)

_ANNOTATION.fields_by_name['rectangle'].message_type = math_pb2._RECTANGLE
_ANNOTATION.fields_by_name['annotatedElementPath'].message_type = dom_pb2._HTMLPATH
DESCRIPTOR.message_types_by_name['Annotation'] = _ANNOTATION

class Annotation(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ANNOTATION
  
  # @@protoc_insertion_point(class_scope:userfeedback.Annotation)

# @@protoc_insertion_point(module_scope)
