# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import common_pb2
import chrome_pb2
import dom_pb2
import math_pb2
import web_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='extension.proto',
  package='userfeedback',
  serialized_pb='\n\x0f\x65xtension.proto\x12\x0cuserfeedback\x1a\x0c\x63ommon.proto\x1a\x0c\x63hrome.proto\x1a\tdom.proto\x1a\nmath.proto\x1a\tweb.proto\"d\n\x1a\x45xtensionPageRequestParams\x12\x39\n\x11\x65xtension_details\x18\x01 \x02(\x0b\x32\x1e.userfeedback.ExtensionDetails\x12\x0b\n\x03url\x18\x02 \x02(\t\"\x83\x01\n\x10PostedScreenshot\x12\x11\n\tmime_type\x18\x01 \x02(\t\x12,\n\ndimensions\x18\x02 \x02(\x0b\x32\x18.userfeedback.Dimensions\x12\x16\n\x0e\x62\x61se64_content\x18\x03 \x01(\t\x12\x16\n\x0e\x62inary_content\x18\x04 \x01(\x0c\"=\n\x0f\x45xtensionErrors\x12\x1a\n\x12number_of_attempts\x18\x01 \x02(\x05\x12\x0e\n\x06\x65rrors\x18\x02 \x02(\t\"\xc2\x02\n\x0f\x45xtensionSubmit\x12-\n\x0b\x63ommon_data\x18\x01 \x02(\x0b\x32\x18.userfeedback.CommonData\x12\'\n\x08web_data\x18\x02 \x02(\x0b\x32\x15.userfeedback.WebData\x12\x0f\n\x07type_id\x18\x03 \x02(\x05\x12\x32\n\nscreenshot\x18\x04 \x01(\x0b\x32\x1e.userfeedback.PostedScreenshot\x12-\n\x0b\x63hrome_data\x18\x0e \x01(\x0b\x32\x18.userfeedback.ChromeData\x12M\n\x1cproduct_specific_binary_data\x18\x0f \x03(\x0b\x32\'.userfeedback.ProductSpecificBinaryData\x12\x14\n\x0c\x63\x61tegory_tag\x18\x10 \x01(\t\"\xe3\x01\n\x0cSuggestQuery\x12-\n\x0b\x63ommon_data\x18\x01 \x02(\x0b\x32\x18.userfeedback.CommonData\x12\'\n\x08web_data\x18\x02 \x02(\x0b\x32\x15.userfeedback.WebData\x12\x0f\n\x07type_id\x18\x03 \x02(\x05\x12;\n\x17html_document_structure\x18\x04 \x01(\x0b\x32\x1a.userfeedback.HtmlDocument\x12-\n\x0b\x63hrome_data\x18\x05 \x01(\x0b\x32\x18.userfeedback.ChromeDataB\x02H\x03')




_EXTENSIONPAGEREQUESTPARAMS = descriptor.Descriptor(
  name='ExtensionPageRequestParams',
  full_name='userfeedback.ExtensionPageRequestParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='extension_details', full_name='userfeedback.ExtensionPageRequestParams.extension_details', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='url', full_name='userfeedback.ExtensionPageRequestParams.url', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=95,
  serialized_end=195,
)


_POSTEDSCREENSHOT = descriptor.Descriptor(
  name='PostedScreenshot',
  full_name='userfeedback.PostedScreenshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='mime_type', full_name='userfeedback.PostedScreenshot.mime_type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dimensions', full_name='userfeedback.PostedScreenshot.dimensions', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='base64_content', full_name='userfeedback.PostedScreenshot.base64_content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='binary_content', full_name='userfeedback.PostedScreenshot.binary_content', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=198,
  serialized_end=329,
)


_EXTENSIONERRORS = descriptor.Descriptor(
  name='ExtensionErrors',
  full_name='userfeedback.ExtensionErrors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='number_of_attempts', full_name='userfeedback.ExtensionErrors.number_of_attempts', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errors', full_name='userfeedback.ExtensionErrors.errors', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=331,
  serialized_end=392,
)


_EXTENSIONSUBMIT = descriptor.Descriptor(
  name='ExtensionSubmit',
  full_name='userfeedback.ExtensionSubmit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='common_data', full_name='userfeedback.ExtensionSubmit.common_data', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='web_data', full_name='userfeedback.ExtensionSubmit.web_data', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type_id', full_name='userfeedback.ExtensionSubmit.type_id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='screenshot', full_name='userfeedback.ExtensionSubmit.screenshot', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='chrome_data', full_name='userfeedback.ExtensionSubmit.chrome_data', index=4,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='product_specific_binary_data', full_name='userfeedback.ExtensionSubmit.product_specific_binary_data', index=5,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='category_tag', full_name='userfeedback.ExtensionSubmit.category_tag', index=6,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=395,
  serialized_end=717,
)


_SUGGESTQUERY = descriptor.Descriptor(
  name='SuggestQuery',
  full_name='userfeedback.SuggestQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='common_data', full_name='userfeedback.SuggestQuery.common_data', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='web_data', full_name='userfeedback.SuggestQuery.web_data', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type_id', full_name='userfeedback.SuggestQuery.type_id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='html_document_structure', full_name='userfeedback.SuggestQuery.html_document_structure', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='chrome_data', full_name='userfeedback.SuggestQuery.chrome_data', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=720,
  serialized_end=947,
)

_EXTENSIONPAGEREQUESTPARAMS.fields_by_name['extension_details'].message_type = web_pb2._EXTENSIONDETAILS
_POSTEDSCREENSHOT.fields_by_name['dimensions'].message_type = math_pb2._DIMENSIONS
_EXTENSIONSUBMIT.fields_by_name['common_data'].message_type = common_pb2._COMMONDATA
_EXTENSIONSUBMIT.fields_by_name['web_data'].message_type = web_pb2._WEBDATA
_EXTENSIONSUBMIT.fields_by_name['screenshot'].message_type = _POSTEDSCREENSHOT
_EXTENSIONSUBMIT.fields_by_name['chrome_data'].message_type = chrome_pb2._CHROMEDATA
_EXTENSIONSUBMIT.fields_by_name['product_specific_binary_data'].message_type = web_pb2._PRODUCTSPECIFICBINARYDATA
_SUGGESTQUERY.fields_by_name['common_data'].message_type = common_pb2._COMMONDATA
_SUGGESTQUERY.fields_by_name['web_data'].message_type = web_pb2._WEBDATA
_SUGGESTQUERY.fields_by_name['html_document_structure'].message_type = dom_pb2._HTMLDOCUMENT
_SUGGESTQUERY.fields_by_name['chrome_data'].message_type = chrome_pb2._CHROMEDATA
DESCRIPTOR.message_types_by_name['ExtensionPageRequestParams'] = _EXTENSIONPAGEREQUESTPARAMS
DESCRIPTOR.message_types_by_name['PostedScreenshot'] = _POSTEDSCREENSHOT
DESCRIPTOR.message_types_by_name['ExtensionErrors'] = _EXTENSIONERRORS
DESCRIPTOR.message_types_by_name['ExtensionSubmit'] = _EXTENSIONSUBMIT
DESCRIPTOR.message_types_by_name['SuggestQuery'] = _SUGGESTQUERY

class ExtensionPageRequestParams(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXTENSIONPAGEREQUESTPARAMS
  
  # @@protoc_insertion_point(class_scope:userfeedback.ExtensionPageRequestParams)

class PostedScreenshot(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POSTEDSCREENSHOT
  
  # @@protoc_insertion_point(class_scope:userfeedback.PostedScreenshot)

class ExtensionErrors(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXTENSIONERRORS
  
  # @@protoc_insertion_point(class_scope:userfeedback.ExtensionErrors)

class ExtensionSubmit(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXTENSIONSUBMIT
  
  # @@protoc_insertion_point(class_scope:userfeedback.ExtensionSubmit)

class SuggestQuery(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SUGGESTQUERY
  
  # @@protoc_insertion_point(class_scope:userfeedback.SuggestQuery)

# @@protoc_insertion_point(module_scope)
