# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='math.proto',
  package='userfeedback',
  serialized_pb='\n\nmath.proto\x12\x0cuserfeedback\"+\n\nDimensions\x12\r\n\x05width\x18\x01 \x02(\x02\x12\x0e\n\x06height\x18\x02 \x02(\x02\"E\n\tRectangle\x12\x0c\n\x04left\x18\x01 \x02(\x02\x12\x0b\n\x03top\x18\x02 \x02(\x02\x12\r\n\x05width\x18\x03 \x02(\x02\x12\x0e\n\x06height\x18\x04 \x02(\x02\x42\x02H\x03')




_DIMENSIONS = descriptor.Descriptor(
  name='Dimensions',
  full_name='userfeedback.Dimensions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='width', full_name='userfeedback.Dimensions.width', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='height', full_name='userfeedback.Dimensions.height', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=71,
)


_RECTANGLE = descriptor.Descriptor(
  name='Rectangle',
  full_name='userfeedback.Rectangle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='left', full_name='userfeedback.Rectangle.left', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='top', full_name='userfeedback.Rectangle.top', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='width', full_name='userfeedback.Rectangle.width', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='height', full_name='userfeedback.Rectangle.height', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=73,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['Dimensions'] = _DIMENSIONS
DESCRIPTOR.message_types_by_name['Rectangle'] = _RECTANGLE

class Dimensions(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DIMENSIONS
  
  # @@protoc_insertion_point(class_scope:userfeedback.Dimensions)

class Rectangle(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RECTANGLE
  
  # @@protoc_insertion_point(class_scope:userfeedback.Rectangle)

# @@protoc_insertion_point(module_scope)
