# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='report.proto',
  package='safe_browsing',
  serialized_pb='\n\x0creport.proto\x12\rsafe_browsing\"\x99\x08\n\x1a\x43lientMalwareReportRequest\x12\x13\n\x0bmalware_url\x18\x01 \x01(\t\x12\x10\n\x08page_url\x18\x02 \x01(\t\x12\x14\n\x0creferrer_url\x18\x03 \x01(\t\x12\x45\n\tresources\x18\x04 \x03(\x0b\x32\x32.safe_browsing.ClientMalwareReportRequest.Resource\x12\x10\n\x08\x63omplete\x18\x05 \x01(\x08\x1a)\n\nHTTPHeader\x12\x0c\n\x04name\x18\x01 \x02(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\x1a\x97\x02\n\x0bHTTPRequest\x12R\n\tfirstline\x18\x01 \x01(\x0b\x32?.safe_browsing.ClientMalwareReportRequest.HTTPRequest.FirstLine\x12\x45\n\x07headers\x18\x02 \x03(\x0b\x32\x34.safe_browsing.ClientMalwareReportRequest.HTTPHeader\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\x12\x12\n\nbodydigest\x18\x04 \x01(\x0c\x12\x12\n\nbodylength\x18\x05 \x01(\x05\x1a\x37\n\tFirstLine\x12\x0c\n\x04verb\x18\x01 \x01(\x0c\x12\x0b\n\x03uri\x18\x02 \x01(\x0c\x12\x0f\n\x07version\x18\x03 \x01(\x0c\x1a\xaf\x02\n\x0cHTTPResponse\x12S\n\tfirstline\x18\x01 \x01(\x0b\x32@.safe_browsing.ClientMalwareReportRequest.HTTPResponse.FirstLine\x12\x45\n\x07headers\x18\x02 \x03(\x0b\x32\x34.safe_browsing.ClientMalwareReportRequest.HTTPHeader\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\x12\x12\n\nbodydigest\x18\x04 \x01(\x0c\x12\x12\n\nbodylength\x18\x05 \x01(\x05\x12\x11\n\tremote_ip\x18\x06 \x01(\x0c\x1a:\n\tFirstLine\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0e\n\x06reason\x18\x02 \x01(\x0c\x12\x0f\n\x07version\x18\x03 \x01(\x0c\x1a\xed\x01\n\x08Resource\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x46\n\x07request\x18\x03 \x01(\x0b\x32\x35.safe_browsing.ClientMalwareReportRequest.HTTPRequest\x12H\n\x08response\x18\x04 \x01(\x0b\x32\x36.safe_browsing.ClientMalwareReportRequest.HTTPResponse\x12\x11\n\tparent_id\x18\x05 \x01(\x05\x12\x11\n\tchild_ids\x18\x06 \x03(\x05\x12\x10\n\x08tag_name\x18\x07 \x01(\tB\x02H\x03')




_CLIENTMALWAREREPORTREQUEST_HTTPHEADER = descriptor.Descriptor(
  name='HTTPHeader',
  full_name='safe_browsing.ClientMalwareReportRequest.HTTPHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='safe_browsing.ClientMalwareReportRequest.HTTPHeader.name', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='safe_browsing.ClientMalwareReportRequest.HTTPHeader.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=212,
  serialized_end=253,
)

_CLIENTMALWAREREPORTREQUEST_HTTPREQUEST_FIRSTLINE = descriptor.Descriptor(
  name='FirstLine',
  full_name='safe_browsing.ClientMalwareReportRequest.HTTPRequest.FirstLine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='verb', full_name='safe_browsing.ClientMalwareReportRequest.HTTPRequest.FirstLine.verb', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='uri', full_name='safe_browsing.ClientMalwareReportRequest.HTTPRequest.FirstLine.uri', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='version', full_name='safe_browsing.ClientMalwareReportRequest.HTTPRequest.FirstLine.version', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=480,
  serialized_end=535,
)

_CLIENTMALWAREREPORTREQUEST_HTTPREQUEST = descriptor.Descriptor(
  name='HTTPRequest',
  full_name='safe_browsing.ClientMalwareReportRequest.HTTPRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='firstline', full_name='safe_browsing.ClientMalwareReportRequest.HTTPRequest.firstline', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='headers', full_name='safe_browsing.ClientMalwareReportRequest.HTTPRequest.headers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='body', full_name='safe_browsing.ClientMalwareReportRequest.HTTPRequest.body', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bodydigest', full_name='safe_browsing.ClientMalwareReportRequest.HTTPRequest.bodydigest', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bodylength', full_name='safe_browsing.ClientMalwareReportRequest.HTTPRequest.bodylength', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CLIENTMALWAREREPORTREQUEST_HTTPREQUEST_FIRSTLINE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=256,
  serialized_end=535,
)

_CLIENTMALWAREREPORTREQUEST_HTTPRESPONSE_FIRSTLINE = descriptor.Descriptor(
  name='FirstLine',
  full_name='safe_browsing.ClientMalwareReportRequest.HTTPResponse.FirstLine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='code', full_name='safe_browsing.ClientMalwareReportRequest.HTTPResponse.FirstLine.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reason', full_name='safe_browsing.ClientMalwareReportRequest.HTTPResponse.FirstLine.reason', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='version', full_name='safe_browsing.ClientMalwareReportRequest.HTTPResponse.FirstLine.version', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=783,
  serialized_end=841,
)

_CLIENTMALWAREREPORTREQUEST_HTTPRESPONSE = descriptor.Descriptor(
  name='HTTPResponse',
  full_name='safe_browsing.ClientMalwareReportRequest.HTTPResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='firstline', full_name='safe_browsing.ClientMalwareReportRequest.HTTPResponse.firstline', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='headers', full_name='safe_browsing.ClientMalwareReportRequest.HTTPResponse.headers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='body', full_name='safe_browsing.ClientMalwareReportRequest.HTTPResponse.body', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bodydigest', full_name='safe_browsing.ClientMalwareReportRequest.HTTPResponse.bodydigest', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bodylength', full_name='safe_browsing.ClientMalwareReportRequest.HTTPResponse.bodylength', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='remote_ip', full_name='safe_browsing.ClientMalwareReportRequest.HTTPResponse.remote_ip', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CLIENTMALWAREREPORTREQUEST_HTTPRESPONSE_FIRSTLINE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=538,
  serialized_end=841,
)

_CLIENTMALWAREREPORTREQUEST_RESOURCE = descriptor.Descriptor(
  name='Resource',
  full_name='safe_browsing.ClientMalwareReportRequest.Resource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='safe_browsing.ClientMalwareReportRequest.Resource.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='url', full_name='safe_browsing.ClientMalwareReportRequest.Resource.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='request', full_name='safe_browsing.ClientMalwareReportRequest.Resource.request', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='response', full_name='safe_browsing.ClientMalwareReportRequest.Resource.response', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='parent_id', full_name='safe_browsing.ClientMalwareReportRequest.Resource.parent_id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='child_ids', full_name='safe_browsing.ClientMalwareReportRequest.Resource.child_ids', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tag_name', full_name='safe_browsing.ClientMalwareReportRequest.Resource.tag_name', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=844,
  serialized_end=1081,
)

_CLIENTMALWAREREPORTREQUEST = descriptor.Descriptor(
  name='ClientMalwareReportRequest',
  full_name='safe_browsing.ClientMalwareReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='malware_url', full_name='safe_browsing.ClientMalwareReportRequest.malware_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='page_url', full_name='safe_browsing.ClientMalwareReportRequest.page_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='referrer_url', full_name='safe_browsing.ClientMalwareReportRequest.referrer_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='resources', full_name='safe_browsing.ClientMalwareReportRequest.resources', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='complete', full_name='safe_browsing.ClientMalwareReportRequest.complete', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CLIENTMALWAREREPORTREQUEST_HTTPHEADER, _CLIENTMALWAREREPORTREQUEST_HTTPREQUEST, _CLIENTMALWAREREPORTREQUEST_HTTPRESPONSE, _CLIENTMALWAREREPORTREQUEST_RESOURCE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=1081,
)

_CLIENTMALWAREREPORTREQUEST_HTTPHEADER.containing_type = _CLIENTMALWAREREPORTREQUEST;
_CLIENTMALWAREREPORTREQUEST_HTTPREQUEST_FIRSTLINE.containing_type = _CLIENTMALWAREREPORTREQUEST_HTTPREQUEST;
_CLIENTMALWAREREPORTREQUEST_HTTPREQUEST.fields_by_name['firstline'].message_type = _CLIENTMALWAREREPORTREQUEST_HTTPREQUEST_FIRSTLINE
_CLIENTMALWAREREPORTREQUEST_HTTPREQUEST.fields_by_name['headers'].message_type = _CLIENTMALWAREREPORTREQUEST_HTTPHEADER
_CLIENTMALWAREREPORTREQUEST_HTTPREQUEST.containing_type = _CLIENTMALWAREREPORTREQUEST;
_CLIENTMALWAREREPORTREQUEST_HTTPRESPONSE_FIRSTLINE.containing_type = _CLIENTMALWAREREPORTREQUEST_HTTPRESPONSE;
_CLIENTMALWAREREPORTREQUEST_HTTPRESPONSE.fields_by_name['firstline'].message_type = _CLIENTMALWAREREPORTREQUEST_HTTPRESPONSE_FIRSTLINE
_CLIENTMALWAREREPORTREQUEST_HTTPRESPONSE.fields_by_name['headers'].message_type = _CLIENTMALWAREREPORTREQUEST_HTTPHEADER
_CLIENTMALWAREREPORTREQUEST_HTTPRESPONSE.containing_type = _CLIENTMALWAREREPORTREQUEST;
_CLIENTMALWAREREPORTREQUEST_RESOURCE.fields_by_name['request'].message_type = _CLIENTMALWAREREPORTREQUEST_HTTPREQUEST
_CLIENTMALWAREREPORTREQUEST_RESOURCE.fields_by_name['response'].message_type = _CLIENTMALWAREREPORTREQUEST_HTTPRESPONSE
_CLIENTMALWAREREPORTREQUEST_RESOURCE.containing_type = _CLIENTMALWAREREPORTREQUEST;
_CLIENTMALWAREREPORTREQUEST.fields_by_name['resources'].message_type = _CLIENTMALWAREREPORTREQUEST_RESOURCE
DESCRIPTOR.message_types_by_name['ClientMalwareReportRequest'] = _CLIENTMALWAREREPORTREQUEST

class ClientMalwareReportRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class HTTPHeader(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CLIENTMALWAREREPORTREQUEST_HTTPHEADER
    
    # @@protoc_insertion_point(class_scope:safe_browsing.ClientMalwareReportRequest.HTTPHeader)
  
  class HTTPRequest(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    
    class FirstLine(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _CLIENTMALWAREREPORTREQUEST_HTTPREQUEST_FIRSTLINE
      
      # @@protoc_insertion_point(class_scope:safe_browsing.ClientMalwareReportRequest.HTTPRequest.FirstLine)
    DESCRIPTOR = _CLIENTMALWAREREPORTREQUEST_HTTPREQUEST
    
    # @@protoc_insertion_point(class_scope:safe_browsing.ClientMalwareReportRequest.HTTPRequest)
  
  class HTTPResponse(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    
    class FirstLine(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _CLIENTMALWAREREPORTREQUEST_HTTPRESPONSE_FIRSTLINE
      
      # @@protoc_insertion_point(class_scope:safe_browsing.ClientMalwareReportRequest.HTTPResponse.FirstLine)
    DESCRIPTOR = _CLIENTMALWAREREPORTREQUEST_HTTPRESPONSE
    
    # @@protoc_insertion_point(class_scope:safe_browsing.ClientMalwareReportRequest.HTTPResponse)
  
  class Resource(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CLIENTMALWAREREPORTREQUEST_RESOURCE
    
    # @@protoc_insertion_point(class_scope:safe_browsing.ClientMalwareReportRequest.Resource)
  DESCRIPTOR = _CLIENTMALWAREREPORTREQUEST
  
  # @@protoc_insertion_point(class_scope:safe_browsing.ClientMalwareReportRequest)

# @@protoc_insertion_point(module_scope)
