# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='debug.proto',
  package='webrtc.audioproc',
  serialized_pb='\n\x0b\x64\x65\x62ug.proto\x12\x10webrtc.audioproc\"\x8e\x01\n\x04Init\x12\x13\n\x0bsample_rate\x18\x01 \x01(\x05\x12\x1a\n\x12\x64\x65vice_sample_rate\x18\x02 \x01(\x05\x12\x1a\n\x12num_input_channels\x18\x03 \x01(\x05\x12\x1b\n\x13num_output_channels\x18\x04 \x01(\x05\x12\x1c\n\x14num_reverse_channels\x18\x05 \x01(\x05\"\x1d\n\rReverseStream\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"^\n\x06Stream\x12\x12\n\ninput_data\x18\x01 \x01(\x0c\x12\x13\n\x0boutput_data\x18\x02 \x01(\x0c\x12\r\n\x05\x64\x65lay\x18\x03 \x01(\x05\x12\r\n\x05\x64rift\x18\x04 \x01(\x11\x12\r\n\x05level\x18\x05 \x01(\x05\"\xee\x01\n\x05\x45vent\x12*\n\x04type\x18\x01 \x02(\x0e\x32\x1c.webrtc.audioproc.Event.Type\x12$\n\x04init\x18\x02 \x01(\x0b\x32\x16.webrtc.audioproc.Init\x12\x37\n\x0ereverse_stream\x18\x03 \x01(\x0b\x32\x1f.webrtc.audioproc.ReverseStream\x12(\n\x06stream\x18\x04 \x01(\x0b\x32\x18.webrtc.audioproc.Stream\"0\n\x04Type\x12\x08\n\x04INIT\x10\x00\x12\x12\n\x0eREVERSE_STREAM\x10\x01\x12\n\n\x06STREAM\x10\x02\x42\x02H\x03')



_EVENT_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='webrtc.audioproc.Event.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='INIT', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REVERSE_STREAM', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STREAM', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=496,
  serialized_end=544,
)


_INIT = descriptor.Descriptor(
  name='Init',
  full_name='webrtc.audioproc.Init',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sample_rate', full_name='webrtc.audioproc.Init.sample_rate', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='device_sample_rate', full_name='webrtc.audioproc.Init.device_sample_rate', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='num_input_channels', full_name='webrtc.audioproc.Init.num_input_channels', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='num_output_channels', full_name='webrtc.audioproc.Init.num_output_channels', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='num_reverse_channels', full_name='webrtc.audioproc.Init.num_reverse_channels', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=176,
)


_REVERSESTREAM = descriptor.Descriptor(
  name='ReverseStream',
  full_name='webrtc.audioproc.ReverseStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data', full_name='webrtc.audioproc.ReverseStream.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=178,
  serialized_end=207,
)


_STREAM = descriptor.Descriptor(
  name='Stream',
  full_name='webrtc.audioproc.Stream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='input_data', full_name='webrtc.audioproc.Stream.input_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='output_data', full_name='webrtc.audioproc.Stream.output_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='delay', full_name='webrtc.audioproc.Stream.delay', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='drift', full_name='webrtc.audioproc.Stream.drift', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='level', full_name='webrtc.audioproc.Stream.level', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=209,
  serialized_end=303,
)


_EVENT = descriptor.Descriptor(
  name='Event',
  full_name='webrtc.audioproc.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='webrtc.audioproc.Event.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='init', full_name='webrtc.audioproc.Event.init', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reverse_stream', full_name='webrtc.audioproc.Event.reverse_stream', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stream', full_name='webrtc.audioproc.Event.stream', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EVENT_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=306,
  serialized_end=544,
)

_EVENT.fields_by_name['type'].enum_type = _EVENT_TYPE
_EVENT.fields_by_name['init'].message_type = _INIT
_EVENT.fields_by_name['reverse_stream'].message_type = _REVERSESTREAM
_EVENT.fields_by_name['stream'].message_type = _STREAM
_EVENT_TYPE.containing_type = _EVENT;
DESCRIPTOR.message_types_by_name['Init'] = _INIT
DESCRIPTOR.message_types_by_name['ReverseStream'] = _REVERSESTREAM
DESCRIPTOR.message_types_by_name['Stream'] = _STREAM
DESCRIPTOR.message_types_by_name['Event'] = _EVENT

class Init(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INIT
  
  # @@protoc_insertion_point(class_scope:webrtc.audioproc.Init)

class ReverseStream(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REVERSESTREAM
  
  # @@protoc_insertion_point(class_scope:webrtc.audioproc.ReverseStream)

class Stream(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STREAM
  
  # @@protoc_insertion_point(class_scope:webrtc.audioproc.Stream)

class Event(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EVENT
  
  # @@protoc_insertion_point(class_scope:webrtc.audioproc.Event)

# @@protoc_insertion_point(module_scope)
