import os
import sys

Import('build_env')
Import('debug')
Import('webrtcpath')
Import('mozsrcpath')
Import('x64')
Import('chromiumbaseincludepath')

if(chromiumbaseincludepath == 'third_party'):
  chromiumbaseincludepath = '../third_party/chromium_base'

include_dirs = [
  '.',
  'config',
  'callcontrol',
  'common',
  'common/socket',
  'common/thread',
  'media',
  'softphonewrapper',
  '../include',
  'sipcc/include',
  'sipcc/cpr/include',
  '../contrib/common',
  'common/browser_logging',                  
  '..',
  '../third_party',
  chromiumbaseincludepath,
  chromiumbaseincludepath + '/base/synchronization'
]


src_files = Glob('config/*.cpp') + \
  Glob('callcontrol/*.cpp') + \
  Glob('common/*.cpp') + \
  Glob('common/thread/*.cpp') + \
  Glob('softphonewrapper/*.cpp')
  

src_files += Glob('media/*.cpp')  
  
# Ensure that the set of includes used here is in sync with the library linked in the Sconscriptlib file

# OpenSource media libraries from Google's WebRTC project 
include_dirs += [
  webrtcpath + '/src',
  webrtcpath + '/src/video_engine/include',
  webrtcpath + '/src/voice_engine/main/interface' 
]

include_dirs += ['media/webrtc']
src_files += Glob('media/webrtc/*.cpp')

env = build_env.Clone(CPPPATH=include_dirs)

env.Library('callcontrol', src_files, LIBS=[], LIBPATH=[])
            
